from __future__ import annotations

import fnmatch
import json
from dataclasses import dataclass, field
from pathlib import Path

from ggraft import glsl
from ggraft.config import Config
from ggraft.errors import TargetError
from ggraft.patching.patch import Injection, Patch


@dataclass
class Step:
    patch: Patch
    injection: Injection


@dataclass
class Plan:
    target: str
    steps: list[Step] = field(default_factory=list)

    @property
    def patch_names(self) -> list[str]:
        seen: list[str] = []
        for step in self.steps:
            if step.patch.name not in seen:
                seen.append(step.patch.name)
        return seen


@dataclass
class Report:
    results: list["Result"] = field(default_factory=list)
    pruned: list[str] = field(default_factory=list)


@dataclass
class Result:
    target: str
    output: Path
    patched: str
    patches: list[str]
    injections: int
    changed: bool
    written: bool = False


def base_files(config: Config) -> list[str]:
    if not config.base_dir.is_dir():
        raise TargetError(
            f"base not found at {config.base_dir}. run 'ggraft pull' first"
        )
    return sorted(
        p.relative_to(config.base_dir).as_posix()
        for p in config.base_dir.rglob("*")
        if p.is_file()
    )


def plan(config: Config, patches: list[Patch], only: list[str] | None = None) -> list[Plan]:
    """Which injections apply to which targets.

    Raises if a target pattern matches nothing, or if a patch applies nowhere.
    """
    available = base_files(config)

    unmatched: list[str] = []
    for patch in patches:
        for pattern in patch.targets:
            if not any(fnmatch.fnmatch(f, pattern) for f in available):
                unmatched.append(f"{patch.name}: {pattern}")
    if unmatched:
        raise TargetError(
            "these target patterns matched nothing in the base:\n  "
            + "\n  ".join(unmatched)
        )

    plans: dict[str, Plan] = {}
    for target in available:
        if only and not any(fnmatch.fnmatch(target, pattern) for pattern in only):
            continue
        for patch in patches:
            if not patch.applies_to(target):
                continue
            entry = plans.setdefault(target, Plan(target=target))
            entry.steps.extend(Step(patch, inj) for inj in patch.injections)
    ordered = [plans[key] for key in sorted(plans)]

    if only is None:
        applied = {step.patch.name for item in ordered for step in item.steps}
        idle = [p.name for p in patches if p.name not in applied]
        if idle:
            raise TargetError(
                "these patches applied to nothing, so their injections never ran:\n  "
                + "\n  ".join(idle)
                + "\n(check 'targets' against 'exclude')"
            )
    return ordered


def _header(config: Config, item: Plan) -> str:
    version = config.version or "unknown"

    return (
        f"\n// DO NOT EDIT\n"
        f"// Generated by ggraft from Minecraft {version}\n"
        f"// Patches: {', '.join(item.patch_names)}"
    )


def apply(config: Config, item: Plan) -> Result:
    source_path = config.base_dir / item.target
    source = source_path.read_text(encoding="utf-8")

    for step in item.steps:
        source = step.injection.apply(source, step.patch.name, item.target)

    if config.header:
        source = glsl.insert_after(source, glsl.header_line(source), _header(config, item))

    output = config.output_dir / item.target
    previous = output.read_text(encoding="utf-8") if output.is_file() else None

    return Result(
        target=item.target,
        output=output,
        patched=source,
        patches=item.patch_names,
        injections=len(item.steps),
        changed=previous != source,
    )


def _read_manifest(path: Path) -> list[str]:
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return [str(t) for t in data.get("targets", [])]
    except (OSError, ValueError):
        return []   # a corrupt manifest must not block a build


def _write_manifest(path: Path, targets: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"targets": sorted(targets)}, indent=2) + "\n", encoding="utf-8")


def _prune(config: Config, keep: set[str]) -> list[str]:
    # only manifest-recorded files are removed; anything else is left alone
    removed: list[str] = []
    for target in _read_manifest(config.manifest):
        if target in keep:
            continue
        stale = config.output_dir / target
        if stale.is_file():
            stale.unlink()
            removed.append(target)
            for parent in stale.parents:
                if parent == config.output_dir or config.output_dir not in parent.parents:
                    break
                if any(parent.iterdir()):
                    break
                parent.rmdir()

    return removed


def run(config: Config, plans: list[Plan], write: bool = True, prune: bool = True) -> Report:
    # prune must be off for a filtered build
    report = Report(results=[apply(config, item) for item in plans])
    if not write:
        return report

    for result in report.results:
        result.output.parent.mkdir(parents=True, exist_ok=True)
        result.output.write_text(result.patched, encoding="utf-8")
        result.written = True

    targets = [r.target for r in report.results]
    if prune:
        report.pruned = _prune(config, set(targets))
        _write_manifest(config.manifest, targets)

    return report
